name: K8s pod
on:
  workflow_dispatch:
jobs:
  check-pods:
    runs-on: self-hosted 
    steps:
      - name: Display CPU information
        run: |
          lscpu
      - name: Gather disk information
        run: |
          lsblk
