name: Kube CI
on:
  workflow_dispatch:
jobs:
  test-on-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Testing on a k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
        id: status
      - run: |
          OUTPUT=kubectl get pods -A | sed -n '2,$p '| awk '{print $4}'
          echo "::set-output name=content::$OUTPUT"
      - name: display string
        run: |
          echo "The string is: ${{ steps.status.outputs.content }}"

