name: Kube CI
on:
  workflow_dispatch:
jobs:
  test-on-cluster:
    runs-on: my_runner
    steps:
      - name: Export Kubeconfig
        run: |
          export KUBECONFIG=/root/.kube/config-k3s:/root/.kube/config-k8s
          STATUS_ARRAY=$(kubectl get pods -A | sed -n '2,$p '| awk '{print $2, $4}')
          echo "STATUS_ARRAY_ENV<<EOF" >> $GITHUB_ENV
          echo $STATUS_ARRAY >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Using environment variable
        run: |
          STATUS="Error"
          for elements in ${STATUS_ARRAY_ENV[@]}
              do
                  if [[ $elements =~ $STATUS ]]
                  then
                    echo "Array element '$STATUS' exists, $elements "
                  else
                    echo "Array element does not exist"
                  fi
          done 
