name: Kube CI
on:
  workflow_dispatch:
jobs:
  test-on-cluster:
    runs-on: my_runner
    steps:
      - name: Export Kubeconfig
        run: |
          export KUBECONFIG=/root/.kube/config-k3s:/root/.kube/config-k8s
      - name: Get pods status
        run: |
          env | grep KUBECONFIG
