name: Kube CI
on:
  workflow_dispatch:
jobs:
  test-on-cluster:
    runs-on: my_runner
    steps:
      - run: |
          export KUBECONFIG=/root/.kube/config-k3s:/root/.kube/config-k8s
          kubectl get pods -A

